name: Build and Release

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executables
        run: |
          mkdir -p release-artifacts
          pyinstaller --onefile main.py --name app-windows
          pyinstaller --onefile main.py --name app-macos
          cp dist/app-windows ./release-artifacts/
          cp dist/app-macos ./release-artifacts/

      - name: Bump version tag automatically
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          default_bump: patch

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release-artifacts/*
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: |
            ✅ Автоматичний реліз для версії ${{ steps.tag_version.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
